### ISSUE TITLE
No info about requirements

### ISSUE THREAD

**Issue by maksiplus19** [lukas-pastva/helm-snowplow#3]
Postgres and Kafka are deployed via k8s operators

Postgres requires Cloudnative PG operator and prometheus stack operator
Kafka requires Strimzi cluster operator

**Comment by lpastva** [comment]
Hello Viktor! Thanks a lot for Your issues!
Sure I will incorporate them.
How did You find me? On Linkedin? Are You also trying to deploy Snowplow cost-effective on k8s? Are you on GCP, AWS, baremetal?

**Comment by lukas-pastva** [comment]
Hello Viktor! Thanks a lot for Your issues!
Sure I will incorporate them.
How did You find me? On Linkedin? Are You also trying to deploy Snowplow cost-effective on k8s? Are you on GCP, AWS, baremetal?

**Comment by maksiplus19** [comment]
Hi. Found your comment on this [discussion](https://discourse.snowplow.io/t/deploying-snowplow-on-kubernetes/861). Yes, I've been asked to deploy Snowplow for researching its features. At this moment I'm using docker cluster, but I'll try to deploy it in cloud cluster (not tcp, aws or azure)

**Comment by lukas-pastva** [comment]
That is so cool, Yo uare actually my first issue creator for all my opensource projects! 
I will implement changes You suggested during weekend.
Also, I have quesiotn for You, are you using any bigdata ? Or are you (same as me) trying to be completely fully on k8s?
Because if fully on k8s, there is a feature that needs to be implemented, I will laso work on it during weekend: https://github.com/snowplow-incubator/snowplow-postgres-loader/issues/75

**Comment by lukas-pastva** [comment]
Ive added the cnpg and strimzi into dependnecies and values.yaml, closing this issue
